### ISSUE TITLE
[Redesign Operation] 

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/catalogue#1027]
Improve the space left hand side of EMIF Catalogue (header). The repeat of the title of email in the email is also a bit weird. May be we should give less emphasis on it, and put it a bit smaller. 

![screen shot 2015-10-04 at 14 13 55](https://cloud.githubusercontent.com/assets/110873/10268010/0aeb5f6a-6aa3-11e5-9b7d-7d2355ecd1e0.png)

**Comment by ribeiroct** [comment]
@bastiao : The issue was browser zoom, right ? Can we close this ?

**Comment by bastiao** [comment]
@ribeiroct indeed, you are right.
