### ISSUE TITLE
[Redesign operation] Menu import/export questionnaire

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/catalogue#1051]
Despite of be a feature of only administrator, it should be clear what they do.

So I suggest to have Export -> Questionnaire (similar with Import). I know that we only own one option, but it follows a structured way.

Another point, how to link a questionnaire with community? 

After release, we also need to think more about "Import -> Fingerprint". But maybe should be discussed in a separated issue.

**Comment by ribeiroct** [comment]
I will make the change.

At the moment, the only way to link a questionnaire with community is through the django admin interface.
