### ISSUE TITLE
QuestionSet list: tooltip to see the rest of information

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/catalogue#1062]
![screen shot 2015-10-10 at 14 03 35](https://cloud.githubusercontent.com/assets/110873/10411291/be18f5da-6f57-11e5-8912-e7baafc9ac64.png)

**Comment by ribeiroct** [comment]
Fixed on https://github.com/bioinformatics-ua/catalogue/commit/db93dd9b67d0e5266c364e560f3fb137eb25bc62
