### ISSUE TITLE
Filters are not working in Safari

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/catalogue#1078]
1. Go to all databases of EMIF-OD
2. Try to filter by What is the database acronym?

Browser: Safari

**Comment by ribeiroct** [comment]
The issue was repeating the database acronym, which was made impossible in https://github.com/bioinformatics-ua/catalogue/commit/8112a476941070ade6aab258757f789a00edbb61 , as database name is mandatory. This can be closed
