### ISSUE TITLE
EMIF Communities

### ISSUE THREAD

**Issue by ribeiroct** [bioinformatics-ua/catalogue#832]
So there's been discussion about developing an solution that would allow several communities in separate spaces but a single deploy point.

All that exists would exist as it is, but inside a community, and communities would be independent from each other. 

There would be a single connection point,and the common database would have differentiated acces to each community, and be able to switch between the communities.

**Comment by bastiao** [comment]
A page with join communities should be created, maybe we can create a separated issue for that before close this one.

**Comment by ribeiroct** [comment]
Note to self: print css should be improved, new templates dont handle printing very well.

**Comment by ribeiroct** [comment]
Alas, this is pull requested, so we can probably close this one,
