### ISSUE TITLE
Service to upload a XLSX and create a questionnaire easily 

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/catalogue#895]
This feature will be available for users belonging to a particular user group.

**Comment by ribeiroct** [comment]
Through webservice ?

**Comment by bastiao** [comment]
Yes, and if we can have a interface it will be nice. Only for a user for a specific group.
We need to start thinking about our group based system and built something to "scale" in the future for more functionality. For instance, restrict users for specific databases could be something large adopted. The community-based is not in the priorities at the moment, but we also need to think that it could be implemented in the future and our core system need to be ready for it.

**Comment by bastiao** [comment]
Can be this issue developed against the master branch?

**Comment by ribeiroct** [comment]
Can i presume this is just a interface to the import_questionnaire command ? Or should we have some kind of validation of uploaded content ?

**Comment by ribeiroct** [comment]
I opened a new issue for the merge situation.

**Comment by bastiao** [comment]
Yes, let's keep it open!

**Comment by bastiao** [comment]
Closing due to: https://github.com/bioinformatics-ua/catalogue/issues/916
