### ISSUE TITLE
Fingerprint: Fix bugs in rendering 

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/catalogue#951]

**Comment by ribeiroct** [comment]
Already done: 
- Made other appear properly as comment of choice Other
- Made choice list have bullet points
- Permissions dont show details on detailed view
- Renamed tag/value to question / answer and added question nr as another column

I'm im missing any from the one's we discussed earlier today ? On this branch there's also included the visual changes of detailed view from #952 , probably makes sense to group all cosmetic changes. Although feature porting still may take some time, so i would suggest do the detailed view visual changes here.
