### ISSUE TITLE
Fingerprint Detailed View: port features from summary view

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/catalogue#952]
Color the answered questions with blue color.

**Comment by ribeiroct** [comment]
Working on this on imp/fingerprinttweaks (forgot to include on commit reference)

**Comment by ribeiroct** [comment]
@bastiao 
Working this on https://github.com/bioinformatics-ua/catalogue/tree/wip/detailedHighlights

Highlights are already ported (though they involved a lot of qprocessor changes) so im waiting on the #953 to be merged to master, and dev synced with master, so I can pull request it to dev. 

Whenever that's done please give me a heads up. Meanwhile i will branch this off to start porting the request functionality
